// Type declarations for the tsuki-sim WASM module loaded at runtime from /public/tsuki-sim/.
// TypeScript cannot resolve absolute URL paths like '/tsuki-sim/tsuki_sim.js' statically,
// so we declare the module shape here.
// The actual implementation is generated by wasm-pack:
//   cd ide/tsuki-sim && wasm-pack build --target web --out-dir ../public/tsuki-sim --out-name tsuki_sim

declare module '/tsuki-sim/tsuki_sim.js' {
  export interface WasmSimulator {
    /** Load transpiled C++ source into the simulator. Returns an error string or "" on success. */
    load(code: string): string
    /** Reset the simulator to its initial state. */
    reset(): void
    /** Execute one interpreter step. Returns a JSON-serialised StepResult. */
    step(): string
    /** Set an analog pin input value (0–1023). */
    set_analog_input(pin: number, value: number): void
    /** Set a digital pin input high or low. */
    set_digital_input(pin: number, high: boolean): void
    /** Drain buffered Serial output. Returns concatenated lines. */
    drain_serial(): string
    /** Returns a JSON object mapping pin numbers to their current values. */
    get_pins(): string
    /** Returns true if code has been loaded successfully. */
    is_loaded(): boolean
    /** Returns the simulated clock in milliseconds. */
    get_ms(): number
    /** Free WASM memory for this instance. */
    free(): void
  }

  export class Simulator implements WasmSimulator {
    constructor()
    load(code: string): string
    reset(): void
    step(): string
    set_analog_input(pin: number, value: number): void
    set_digital_input(pin: number, high: boolean): void
    drain_serial(): string
    get_pins(): string
    is_loaded(): boolean
    get_ms(): number
    free(): void
  }

  /** wasm-bindgen init function — call once with the .wasm URL before using Simulator. */
  export default function init(wasmUrl?: string | URL): Promise<unknown>
}