"use client";
import { useState } from "react";

type Token = [string, string];
type CLine = Token[] | null;

const EXAMPLES = [
  {
    tab: "blink.go",
    go: [
      [["go-kw","package"],["go-id"," main"]] as Token[],
      null,
      [["go-kw","import"],["go-id"," ("]],
      [["go-id","    "],["go-str",'"arduino"']],
      [["go-id","    "],["go-str",'"time"']],
      [["go-id",")"]],
      null,
      [["go-kw","const"],["go-id"," LED = "],["go-num","13"]],
      null,
      [["go-kw","func"],["go-id"," "],["go-fn","setup"],["go-id","() {"]],
      [["go-id","    "],["go-pkg","arduino"],["go-id","."],["go-fn","pinMode"],["go-id","(LED, "],["go-pkg","arduino"],["go-id",".OUTPUT)"]],
      [["go-id","}"]],
      null,
      [["go-kw","func"],["go-id"," "],["go-fn","loop"],["go-id","() {"]],
      [["go-id","    "],["go-pkg","arduino"],["go-id","."],["go-fn","digitalWrite"],["go-id","(LED, "],["go-pkg","arduino"],["go-id",".HIGH)"]],
      [["go-id","    "],["go-pkg","time"],["go-id","."],["go-fn","Sleep"],["go-id","("],["go-num","500"],["go-id",")"]],
      [["go-id","    "],["go-pkg","arduino"],["go-id","."],["go-fn","digitalWrite"],["go-id","(LED, "],["go-pkg","arduino"],["go-id",".LOW)"]],
      [["go-id","    "],["go-pkg","time"],["go-id","."],["go-fn","Sleep"],["go-id","("],["go-num","500"],["go-id",")"]],
      [["go-id","}"]],
    ] as CLine[],
    cpp: [
      [["cpp-pp","#include"],["cpp-id"," <Arduino.h>"]] as Token[],
      null,
      [["cpp-cm","// generated by tsuki v0.1.0"]],
      null,
      [["cpp-kw","const"],["cpp-id"," "],["cpp-ty","int"],["cpp-id"," LED = "],["cpp-num","13"],["cpp-id",";"]],
      null,
      [["cpp-kw","void"],["cpp-id"," "],["cpp-fn","setup"],["cpp-id","() {"]],
      [["cpp-id","    "],["cpp-fn","pinMode"],["cpp-id","(LED, OUTPUT);"]],
      [["cpp-id","}"]],
      null,
      [["cpp-kw","void"],["cpp-id"," "],["cpp-fn","loop"],["cpp-id","() {"]],
      [["cpp-id","    "],["cpp-fn","digitalWrite"],["cpp-id","(LED, HIGH);"]],
      [["cpp-id","    "],["cpp-fn","delay"],["cpp-id","(500);"]],
      [["cpp-id","    "],["cpp-fn","digitalWrite"],["cpp-id","(LED, LOW);"]],
      [["cpp-id","    "],["cpp-fn","delay"],["cpp-id","(500);"]],
      [["cpp-id","}"]],
    ] as CLine[],
  },
  {
    tab: "sensor.go",
    go: [
      [["go-kw","package"],["go-id"," main"]] as Token[],
      null,
      [["go-kw","import"],["go-id"," ("]],
      [["go-id","    "],["go-str",'"arduino"']],
      [["go-id","    "],["go-str",'"fmt"']],
      [["go-id",")"]],
      null,
      [["go-kw","func"],["go-id"," "],["go-fn","setup"],["go-id","() {"]],
      [["go-id","    "],["go-pkg","arduino"],["go-id",".Serial.Begin("],["go-num","9600"],["go-id",")"]],
      [["go-id","}"]],
      null,
      [["go-kw","func"],["go-id"," "],["go-fn","loop"],["go-id","() {"]],
      [["go-id","    val := "],["go-pkg","arduino"],["go-id","."],["go-fn","analogRead"],["go-id","("],["go-num","0"],["go-id",")"]],
      [["go-id","    "],["go-pkg","fmt"],["go-id","."],["go-fn","Printf"],["go-id","("],["go-str",'"Sensor: %d\\n"'],["go-id",", val)"]],
      [["go-id","    "],["go-pkg","arduino"],["go-id","."],["go-fn","delay"],["go-id","("],["go-num","100"],["go-id",")"]],
      [["go-id","}"]],
    ] as CLine[],
    cpp: [
      [["cpp-pp","#include"],["cpp-id"," <Arduino.h>"]] as Token[],
      null,
      [["cpp-cm","// generated by tsuki v0.1.0"]],
      null,
      [["cpp-kw","void"],["cpp-id"," "],["cpp-fn","setup"],["cpp-id","() {"]],
      [["cpp-id","    "],["cpp-id","Serial.begin(9600);"]],
      [["cpp-id","}"]],
      null,
      [["cpp-kw","void"],["cpp-id"," "],["cpp-fn","loop"],["cpp-id","() {"]],
      [["cpp-id","    "],["cpp-ty","int"],["cpp-id"," val = "],["cpp-fn","analogRead"],["cpp-id","(0);"]],
      [["cpp-id","    "],["cpp-ty","char"],["cpp-id"," _buf[64];"]],
      [["cpp-id","    "],["cpp-fn","snprintf"],["cpp-id","(_buf, 64, "],["cpp-str",'"Sensor: %d\\n"'],["cpp-id",", val);"]],
      [["cpp-id","    "],["cpp-id","Serial.print(_buf);"]],
      [["cpp-id","    "],["cpp-fn","delay"],["cpp-id","(100);"]],
      [["cpp-id","}"]],
    ] as CLine[],
  },
];

function CodeLine({ line, n }: { line: CLine; n: number }) {
  return (
    <div style={{ display: "flex", gap: 16, padding: "1.5px 16px" }}>
      <span style={{ minWidth: 22, textAlign: "right", color: "#222", userSelect: "none", flexShrink: 0, fontFamily: "var(--f-mono)", fontSize: 11 }}>{n}</span>
      <span style={{ fontFamily: "var(--f-mono)", fontSize: 12.5, lineHeight: "20px" }}>
        {line ? line.map(([cls, txt], i) => <span key={i} className={cls}>{txt}</span>) : null}
      </span>
    </div>
  );
}

export default function CodeDemo() {
  const [idx, setIdx] = useState(0);
  const ex = EXAMPLES[idx];

  return (
    <section className="section" style={{ borderTop: "1px solid rgba(255,255,255,0.06)" }}>
      <div className="container">

        <div className="reveal" style={{ marginBottom: 56, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 40, alignItems: "end" }}>
          <div>
            <div style={{ fontFamily: "var(--f-mono)", fontSize: 11, letterSpacing: "0.1em", color: "var(--accent)", marginBottom: 16, textTransform: "uppercase" }}>Transpiler</div>
            <h2 className="t-h2">Go <span style={{ color: "#333" }}>→</span> C++.<br />Automatically.</h2>
          </div>
          <p className="t-body">
            tsuki-core is a full recursive-descent parser for a Go subset — not a wrapper, not a template.
            It produces clean, readable C++ that you can inspect and ship.
          </p>
        </div>

        {/* Tabs */}
        <div className="reveal" style={{ display: "flex", gap: 6, marginBottom: 16 }}>
          {EXAMPLES.map((e, i) => (
            <button key={e.tab} onClick={() => setIdx(i)} style={{ padding: "5px 14px", background: idx === i ? "rgba(255,255,255,0.08)" : "transparent", border: "1px solid", borderColor: idx === i ? "rgba(255,255,255,0.14)" : "rgba(255,255,255,0.06)", borderRadius: 6, fontFamily: "var(--f-mono)", fontSize: 11, color: idx === i ? "#fff" : "#444", cursor: "pointer", transition: "all 0.15s ease" }}>
              {e.tab}
            </button>
          ))}
        </div>

        {/* Side by side */}
        <div className="reveal" style={{ display: "grid", gridTemplateColumns: "1fr 40px 1fr", alignItems: "stretch" }}>

          <div style={{ background: "#0a0a0a", border: "1px solid rgba(255,255,255,0.08)", borderRight: "none", borderRadius: "8px 0 0 8px", overflow: "hidden" }}>
            <div style={{ padding: "9px 16px", background: "#060606", borderBottom: "1px solid rgba(255,255,255,0.06)", display: "flex", alignItems: "center", gap: 8 }}>
              <div style={{ width: 7, height: 7, borderRadius: "50%", background: "#50fa7b" }} />
              <span style={{ fontFamily: "var(--f-mono)", fontSize: 11, color: "#555" }}>{ex.tab}</span>
            </div>
            <div style={{ padding: "10px 0", overflowX: "auto" }}>
              {ex.go.map((l, i) => <CodeLine key={i} line={l} n={i + 1} />)}
            </div>
          </div>

          <div style={{ display: "flex", alignItems: "center", justifyContent: "center", background: "#060606", borderTop: "1px solid rgba(255,255,255,0.08)", borderBottom: "1px solid rgba(255,255,255,0.08)" }}>
            <span style={{ fontFamily: "var(--f-mono)", fontSize: 16, color: "var(--accent)", opacity: 0.6 }}>→</span>
          </div>

          <div style={{ background: "#0a0a0a", border: "1px solid rgba(255,255,255,0.08)", borderLeft: "none", borderRadius: "0 8px 8px 0", overflow: "hidden" }}>
            <div style={{ padding: "9px 16px", background: "#060606", borderBottom: "1px solid rgba(255,255,255,0.06)", display: "flex", alignItems: "center", gap: 8 }}>
              <div style={{ width: 7, height: 7, borderRadius: "50%", background: "#82aaff" }} />
              <span style={{ fontFamily: "var(--f-mono)", fontSize: 11, color: "#555" }}>build/main/sketch.ino.cpp</span>
            </div>
            <div style={{ padding: "10px 0", overflowX: "auto" }}>
              {ex.cpp.map((l, i) => <CodeLine key={i} line={l} n={i + 1} />)}
            </div>
          </div>
        </div>

        {/* Package table */}
        <div className="reveal" style={{ marginTop: 32, background: "#0a0a0a", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 8, overflow: "hidden" }}>
          <div style={{ padding: "12px 20px", borderBottom: "1px solid rgba(255,255,255,0.06)", display: "flex", alignItems: "center", gap: 10 }}>
            <span style={{ fontFamily: "var(--f-sans)", fontSize: 13, fontWeight: 600, color: "#fff" }}>Built-in Go packages</span>
            <span style={{ fontFamily: "var(--f-mono)", fontSize: 11, color: "#333" }}>— no imports needed at the toolchain level</span>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))" }}>
            {[
              { imp: '"arduino"',      maps: 'pinMode, digitalWrite, analogRead…' },
              { imp: '"fmt"',          maps: 'Serial.print, Serial.println…' },
              { imp: '"time"',         maps: 'delay(), millis(), micros()' },
              { imp: '"math"',         maps: '<math.h>: sin, cos, sqrt, pow…' },
              { imp: '"strconv"',      maps: 'String(), .toInt(), .toFloat()' },
              { imp: '"wire"',         maps: 'Wire.begin(), Wire.write()… (I2C)' },
              { imp: '"spi"',          maps: 'SPI.begin(), SPI.transfer()…' },
              { imp: '"serial"',       maps: 'Serial.begin(), .println()…' },
              { imp: '"servo"',        maps: 'Servo.attach(), Servo.write()…' },
              { imp: '"LiquidCrystal"',maps: 'LiquidCrystal.begin(), .print()…' },
            ].map((r, i) => (
              <div key={i} style={{ padding: "10px 20px", borderRight: "1px solid rgba(255,255,255,0.04)", borderBottom: "1px solid rgba(255,255,255,0.04)" }}>
                <div style={{ fontFamily: "var(--f-mono)", fontSize: 12, color: "var(--accent)", marginBottom: 3 }}>{r.imp}</div>
                <div style={{ fontFamily: "var(--f-mono)", fontSize: 10, color: "#444", lineHeight: 1.5 }}>{r.maps}</div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
