// ─────────────────────────────────────────────────────────────────────────────
//  tsuki :: python :: transpiler
//
//  Converts a PyProgram (Python AST) → Arduino C++ source string.
//
//  Package mapping reuses the same Runtime as the Go transpiler, so all
//  tsukilib packages work transparently with Python source files.
// ─────────────────────────────────────────────────────────────────────────────

use std::collections::{HashMap, HashSet};
use std::fmt::Write as FmtWrite;

use crate::error::{Result, TsukiError};
use crate::runtime::Runtime;
use crate::transpiler::TranspileConfig;
use super::ast::*;

// ── Transpiler struct ─────────────────────────────────────────────────────────

pub struct PyTranspiler {
    cfg:      TranspileConfig,
    rt:       Runtime,
    indent:   usize,
    includes: HashSet<String>,
    /// Which Python module names are imported (e.g. "arduino", "time", "fmt")
    imports:  HashSet<String>,
    /// Maps module alias → canonical name (from `import foo as f`)
    aliases:  HashMap<String, String>,
    /// Inferred variable types: name → C++ type string
    var_types: HashMap<String, String>,
}

impl PyTranspiler {
    pub fn new(cfg: TranspileConfig, rt: Runtime) -> Self {
        Self {
            cfg,
            rt,
            indent: 0,
            includes: HashSet::new(),
            imports: HashSet::new(),
            aliases: HashMap::new(),
            var_types: HashMap::new(),
        }
    }

    // ── Entry point ───────────────────────────────────────────────────────────

    pub fn generate(&mut self, prog: &PyProgram) -> Result<String> {
        // Register imports
        for imp in &prog.imports {
            let canon = imp.alias.as_deref().map(|_| imp.module.as_str()).unwrap_or(&imp.module);
            let name = imp.module.split('.').next().unwrap_or(&imp.module).to_owned();
            self.imports.insert(name.clone());
            if let Some(alias) = &imp.alias {
                self.aliases.insert(alias.clone(), imp.module.clone());
            }
            // Register include from runtime if available
            if let Some(pkg) = self.rt.packages.get(&name) {
                if let Some(h) = &pkg.header {
                    self.includes.insert(h.clone());
                }
            }
            // Also check `from foo import bar` names
            for item in &imp.names {
                let fq = format!("{}.{}", imp.module, item);
                if let Some(pkg) = self.rt.packages.get(&fq) {
                    if let Some(h) = &pkg.header {
                        self.includes.insert(h.clone());
                    }
                }
            }
        }
        self.includes.insert("Arduino.h".into());

        // Two-pass: collect variable types from globals first
        for stmt in &prog.globals {
            self.infer_var_type_stmt(stmt);
        }

        // ── Build output ──────────────────────────────────────────────────────
        let mut out = String::new();

        // Header comment
        out += &format!(
            "// Generated by tsuki (Python → C++) — board: {}\n// DO NOT EDIT — edit the .py source instead\n\n",
            self.cfg.board
        );

        // Includes
        let mut incs: Vec<_> = self.includes.iter().cloned().collect();
        incs.sort();
        for i in &incs { let _ = writeln!(out, "#include <{}>", i); }
        out += "\n";

        // Globals
        for stmt in &prog.globals {
            out += &self.emit_stmt(stmt)?;
        }
        if !prog.globals.is_empty() { out += "\n"; }

        // Forward declarations (non-setup/loop functions)
        for f in &prog.functions {
            if f.name != "setup" && f.name != "loop" {
                out += &self.emit_func_fwd(f)?;
            }
        }
        if prog.functions.iter().any(|f| f.name != "setup" && f.name != "loop") {
            out += "\n";
        }

        // Functions — setup/loop go last (Arduino convention)
        let mut ordered: Vec<&PyFuncDef> = prog.functions.iter()
            .filter(|f| f.name != "setup" && f.name != "loop")
            .collect();
        if let Some(s) = prog.functions.iter().find(|f| f.name == "setup") { ordered.push(s); }
        if let Some(l) = prog.functions.iter().find(|f| f.name == "loop")  { ordered.push(l); }

        for f in ordered {
            out += &self.emit_func(f)?;
        }

        Ok(out)
    }

    // ── Forward declaration ───────────────────────────────────────────────────

    fn emit_func_fwd(&self, f: &PyFuncDef) -> Result<String> {
        let ret = self.py_type_to_cpp(f.return_type.as_deref().unwrap_or("void"));
        let params = self.emit_params(&f.params)?;
        Ok(format!("{} {}({});\n", ret, f.name, params))
    }

    // ── Function emission ─────────────────────────────────────────────────────

    fn emit_func(&mut self, f: &PyFuncDef) -> Result<String> {
        let ret = self.py_type_to_cpp(f.return_type.as_deref().unwrap_or("void"));
        let params = self.emit_params(&f.params)?;
        let mut out = format!("{} {}({}) {{\n", ret, f.name, params);
        self.indent += 1;
        for stmt in &f.body {
            out += &self.emit_stmt(stmt)?;
        }
        self.indent -= 1;
        out += "}\n\n";
        Ok(out)
    }

    fn emit_params(&self, params: &[PyParam]) -> Result<String> {
        let mut parts = Vec::new();
        for p in params {
            let ty = self.py_type_to_cpp(p.ann.as_deref().unwrap_or("auto"));
            parts.push(format!("{} {}", ty, p.name));
        }
        Ok(parts.join(", "))
    }

    // ── Statement emission ────────────────────────────────────────────────────

    fn emit_stmt(&mut self, stmt: &PyStmt) -> Result<String> {
        let ind = "    ".repeat(self.indent);
        match stmt {
            PyStmt::Comment(c) => Ok(format!("{}// {}\n", ind, c)),

            PyStmt::Pass(_) => Ok(format!("{}/* pass */\n", ind)),

            PyStmt::Break(_) => Ok(format!("{}break;\n", ind)),

            PyStmt::Continue(_) => Ok(format!("{}continue;\n", ind)),

            PyStmt::Global { names, .. } => {
                // In C++ globals are already global — emit a comment
                Ok(format!("{}// global: {}\n", ind, names.join(", ")))
            }

            PyStmt::Return { value, .. } => {
                match value {
                    None    => Ok(format!("{}return;\n", ind)),
                    Some(e) => Ok(format!("{}return {};\n", ind, self.emit_expr(e)?)),
                }
            }

            PyStmt::Assign { target, ann, value, .. } => {
                let cpp_type = ann.as_deref()
                    .map(|a| self.py_type_to_cpp(a))
                    .or_else(|| {
                        // Infer type from value
                        value.as_ref().map(|v| self.infer_expr_type(v))
                    });

                match (cpp_type, value) {
                    (Some(ty), Some(v)) => {
                        let val = self.emit_expr(v)?;
                        // Store type for later use
                        self.var_types.insert(target.clone(), ty.clone());
                        Ok(format!("{}{} {} = {};\n", ind, ty, target, val))
                    }
                    (None, Some(v)) => {
                        let val = self.emit_expr(v)?;
                        Ok(format!("{}auto {} = {};\n", ind, target, val))
                    }
                    (Some(ty), None) => {
                        self.var_types.insert(target.clone(), ty.clone());
                        Ok(format!("{}{} {};\n", ind, ty, target))
                    }
                    (None, None) => {
                        Ok(format!("{}/* {} */\n", ind, target))
                    }
                }
            }

            PyStmt::AugAssign { target, op, value, .. } => {
                let val = self.emit_expr(value)?;
                let op_str = op.to_cpp();
                Ok(format!("{}{} {}= {};\n", ind, target, op_str, val))
            }

            PyStmt::Expr(e) => {
                let s = self.emit_expr(e)?;
                Ok(format!("{}{};\n", ind, s))
            }

            PyStmt::If { cond, body, elif_clauses, else_body, .. } => {
                let mut out = format!("{}if ({}) {{\n", ind, self.emit_expr(cond)?);
                self.indent += 1;
                for s in body { out += &self.emit_stmt(s)?; }
                self.indent -= 1;
                out += &format!("{}}}", ind);

                for (ec, eb) in elif_clauses {
                    out += &format!(" else if ({}) {{\n", self.emit_expr(ec)?);
                    self.indent += 1;
                    for s in eb { out += &self.emit_stmt(s)?; }
                    self.indent -= 1;
                    out += &format!("{}}}", ind);
                }

                if !else_body.is_empty() {
                    out += " else {\n";
                    self.indent += 1;
                    for s in else_body { out += &self.emit_stmt(s)?; }
                    self.indent -= 1;
                    out += &format!("{}}}", ind);
                }
                out += "\n";
                Ok(out)
            }

            PyStmt::While { cond, body, .. } => {
                let mut out = format!("{}while ({}) {{\n", ind, self.emit_expr(cond)?);
                self.indent += 1;
                for s in body { out += &self.emit_stmt(s)?; }
                self.indent -= 1;
                out += &format!("{}}}\n", ind);
                Ok(out)
            }

            PyStmt::For { var, iter, body, .. } => {
                let for_header = self.emit_for_header(var, iter)?;
                let mut out = format!("{}{} {{\n", ind, for_header);
                self.indent += 1;
                for s in body { out += &self.emit_stmt(s)?; }
                self.indent -= 1;
                out += &format!("{}}}\n", ind);
                Ok(out)
            }
        }
    }

    /// Emit the `for (...)` header for Python `for var in iter`.
    fn emit_for_header(&mut self, var: &str, iter: &PyExpr) -> Result<String> {
        // Detect `range(n)`, `range(a, b)`, `range(a, b, step)`
        if let PyExpr::Call { func, args, .. } = iter {
            let fname = self.flatten_expr_name(func);
            if fname == "range" {
                return match args.len() {
                    1 => {
                        let end = self.emit_expr(&args[0])?;
                        Ok(format!("for (int {} = 0; {} < {}; {}++)", var, var, end, var))
                    }
                    2 => {
                        let start = self.emit_expr(&args[0])?;
                        let end   = self.emit_expr(&args[1])?;
                        Ok(format!("for (int {} = {}; {} < {}; {}++)", var, start, var, end, var))
                    }
                    3 => {
                        let start = self.emit_expr(&args[0])?;
                        let end   = self.emit_expr(&args[1])?;
                        let step  = self.emit_expr(&args[2])?;
                        Ok(format!("for (int {} = {}; {} < {}; {} += {})", var, start, var, end, var, step))
                    }
                    _ => Err(TsukiError::Codegen("range() takes 1-3 arguments".into())),
                };
            }
            // enumerate(iterable) — simplified, just iterate with index
            if fname == "enumerate" && !args.is_empty() {
                let iter_expr = self.emit_expr(&args[0])?;
                return Ok(format!(
                    "for (size_t {} = 0; {} < sizeof({}) / sizeof({}[0]); {}++)",
                    var, var, iter_expr, iter_expr, var
                ));
            }
        }

        // Fallback: range-based for over array/pointer
        let iter_s = self.emit_expr(iter)?;
        Ok(format!("for (auto {} : {})", var, iter_s))
    }

    /// Extract a dotted name from an expression (for function name detection).
    fn flatten_expr_name(&self, expr: &PyExpr) -> String {
        match expr {
            PyExpr::Ident(s) => s.clone(),
            PyExpr::Attr { obj, attr, .. } => format!("{}.{}", self.flatten_expr_name(obj), attr),
            _ => String::new(),
        }
    }

    // ── Expression emission ───────────────────────────────────────────────────

    pub fn emit_expr(&mut self, expr: &PyExpr) -> Result<String> {
        match expr {
            PyExpr::Int(v)   => Ok(v.to_string()),
            PyExpr::Float(v) => {
                let s = format!("{}", v);
                // Ensure C++ recognizes it as a float literal
                if s.contains('.') { Ok(s) } else { Ok(format!("{}.0", s)) }
            }
            PyExpr::Bool(b)  => Ok(if *b { "true" } else { "false" }.into()),
            PyExpr::None     => Ok("NULL".into()),
            PyExpr::Str(s)   => Ok(format!("\"{}\"", s.replace('"', "\\\""))),
            PyExpr::Ident(s) => Ok(self.resolve_ident(s)),
            PyExpr::List(elems) => {
                let parts: Result<Vec<_>> = elems.iter().map(|e| self.emit_expr(e)).collect();
                Ok(format!("{{{}}}", parts?.join(", ")))
            }

            PyExpr::Attr { obj, attr, .. } => {
                let obj_name = self.flatten_expr_name(obj);
                // Check if it's a package constant (e.g. arduino.HIGH, arduino.OUTPUT)
                let resolved_mod = self.resolve_module(&obj_name);
                if let Some(pkg) = self.rt.packages.get(&resolved_mod) {
                    if let Some(c) = pkg.constants.get(attr.as_str()) {
                        return Ok(c.clone());
                    }
                }
                // Default: obj.attr → obj.attr
                let obj_s = self.emit_expr(obj)?;
                Ok(format!("{}.{}", obj_s, attr))
            }

            PyExpr::Call { func, args, .. } => self.emit_call(func, args),

            PyExpr::Subscript { obj, index, .. } => {
                let o = self.emit_expr(obj)?;
                let i = self.emit_expr(index)?;
                Ok(format!("{}[{}]", o, i))
            }

            PyExpr::BinOp { left, op, right, .. } => {
                // Special-case ** (pow) → pow(left, right)
                if *op == BinOp::Pow {
                    let l = self.emit_expr(left)?;
                    let r = self.emit_expr(right)?;
                    self.includes.insert("math.h".into());
                    return Ok(format!("pow({}, {})", l, r));
                }
                let l = self.emit_expr(left)?;
                let r = self.emit_expr(right)?;
                Ok(format!("({} {} {})", l, op.to_cpp(), r))
            }

            PyExpr::UnaryOp { op, operand, .. } => {
                let o = self.emit_expr(operand)?;
                let op_str = match op {
                    UnaryOp::Not    => "!",
                    UnaryOp::Neg    => "-",
                    UnaryOp::BitNot => "~",
                };
                Ok(format!("({}{})", op_str, o))
            }

            PyExpr::FStr { parts, .. } => {
                // Simplified f-string → snprintf style
                let mut fmt_str = String::new();
                let mut fmt_args = Vec::new();
                for part in parts {
                    match part {
                        FStrPart::Literal(s) => fmt_str.push_str(s),
                        FStrPart::Expr(e) => {
                            fmt_str.push_str("%s");
                            fmt_args.push(format!("String({})", self.emit_expr(e)?));
                        }
                    }
                }
                if fmt_args.is_empty() {
                    Ok(format!("\"{}\"", fmt_str))
                } else {
                    Ok(format!(
                        "([&]({{ char _b[256]; snprintf(_b, sizeof(_b), \"{}\", {}); return String(_b); }})())",
                        fmt_str,
                        fmt_args.join(", ")
                    ))
                }
            }
        }
    }

    // ── Call dispatch ─────────────────────────────────────────────────────────

    fn emit_call(&mut self, func: &PyExpr, args: &[PyExpr]) -> Result<String> {
        let fname = self.flatten_expr_name(func);

        // ── Built-in Python functions ─────────────────────────────────────────
        match fname.as_str() {
            "print" => {
                // print(x) → Serial.println(x)
                // print(x, end="") → Serial.print(x)
                let args_s: Result<Vec<_>> = args.iter().map(|a| self.emit_expr(a)).collect();
                let args_s = args_s?;
                if args_s.len() == 1 {
                    return Ok(format!("Serial.println({})", args_s[0]));
                }
                return Ok(format!("Serial.print({})", args_s.join(", ")));
            }
            "len" => {
                if let Some(a) = args.first() {
                    let s = self.emit_expr(a)?;
                    return Ok(format!("(sizeof({}) / sizeof({}[0]))", s, s));
                }
            }
            "int" => {
                if let Some(a) = args.first() {
                    let s = self.emit_expr(a)?;
                    return Ok(format!("((int)({}))", s));
                }
            }
            "float" => {
                if let Some(a) = args.first() {
                    let s = self.emit_expr(a)?;
                    return Ok(format!("((float)({}))", s));
                }
            }
            "str" => {
                if let Some(a) = args.first() {
                    let s = self.emit_expr(a)?;
                    return Ok(format!("String({})", s));
                }
            }
            "bool" => {
                if let Some(a) = args.first() {
                    let s = self.emit_expr(a)?;
                    return Ok(format!("((bool)({}))", s));
                }
            }
            "abs" => {
                if let Some(a) = args.first() {
                    let s = self.emit_expr(a)?;
                    return Ok(format!("abs({})", s));
                }
            }
            "min" => {
                let parts: Result<Vec<_>> = args.iter().map(|a| self.emit_expr(a)).collect();
                return Ok(format!("min({})", parts?.join(", ")));
            }
            "max" => {
                let parts: Result<Vec<_>> = args.iter().map(|a| self.emit_expr(a)).collect();
                return Ok(format!("max({})", parts?.join(", ")));
            }
            "map" | "constrain" => {
                let parts: Result<Vec<_>> = args.iter().map(|a| self.emit_expr(a)).collect();
                return Ok(format!("{}({})", fname, parts?.join(", ")));
            }
            _ => {}
        }

        // ── Module-qualified call: pkg.Func(args) ─────────────────────────────
        // We must extract everything we need from `self.rt` *before* calling
        // `self.emit_expr`, because emit_expr takes `&mut self` and the borrow
        // checker would otherwise see a simultaneous shared borrow on `self.rt`
        // and a mutable borrow on `self`.
        if let Some(dot) = fname.find('.') {
            let mod_name = &fname[..dot];
            let fn_name  = &fname[dot+1..];
            let resolved = self.resolve_module(mod_name);

            // --- Phase 1: immutable snapshot from rt (borrow ends at end of block)
            let maybe_fn_map_and_header: Option<(crate::runtime::FnMap, Option<String>)> =
                self.rt.packages.get(&resolved).and_then(|pkg| {
                    pkg.functions.get(fn_name)
                        .map(|fm| (fm.clone(), pkg.header.clone()))
                });

            let maybe_constant: Option<String> =
                if maybe_fn_map_and_header.is_none() {
                    self.rt.packages.get(&resolved)
                        .and_then(|pkg| pkg.constants.get(fn_name).cloned())
                } else {
                    None
                };

            // --- Phase 2: use &mut self freely now that the rt borrow is gone
            if let Some((fn_map, header)) = maybe_fn_map_and_header {
                let cpp_args: Vec<String> = args.iter()
                    .map(|a| self.emit_expr(a))
                    .collect::<Result<Vec<_>>>()?;
                if let Some(h) = header {
                    self.includes.insert(h);
                }
                return Ok(fn_map.apply(&cpp_args));
            }
            if let Some(c) = maybe_constant {
                return Ok(c);
            }
        }

        // ── Fallback: emit as-is ──────────────────────────────────────────────
        let parts: Result<Vec<_>> = args.iter().map(|a| self.emit_expr(a)).collect();
        let func_s = self.emit_expr(func)?;
        Ok(format!("{}({})", func_s, parts?.join(", ")))
    }

    // ── Name resolution ───────────────────────────────────────────────────────

    /// Resolve a Python identifier to its C++ equivalent.
    fn resolve_ident(&self, name: &str) -> String {
        // Check if it's a known constant in any imported package
        for mod_name in &self.imports {
            if let Some(pkg) = self.rt.packages.get(mod_name.as_str()) {
                if let Some(c) = pkg.constants.get(name) {
                    return c.clone();
                }
            }
        }
        // Direct constant check from `from foo import BAR`
        // (already flattened by parser — name is used directly)
        name.to_owned()
    }

    /// Resolve a module name through aliases.
    fn resolve_module(&self, name: &str) -> String {
        self.aliases.get(name).cloned().unwrap_or_else(|| name.to_owned())
    }

    // ── Type system ───────────────────────────────────────────────────────────

    /// Convert a Python type annotation to a C++ type string.
    fn py_type_to_cpp(&self, ann: &str) -> String {
        match ann {
            "int"           => "int".into(),
            "float"         => "float".into(),
            "bool"          => "bool".into(),
            "str"           => if self.cfg.arduino_string { "String".into() } else { "const char*".into() },
            "bytes"         => "uint8_t*".into(),
            "None"          => "void".into(),
            "void"          => "void".into(),
            "auto"          => "auto".into(),
            // Explicit C-style integer types (used via tsuki type hints)
            "int8"          => "int8_t".into(),
            "int16"         => "int16_t".into(),
            "int32"         => "int32_t".into(),
            "int64"         => "int64_t".into(),
            "uint8"         => "uint8_t".into(),
            "uint16"        => "uint16_t".into(),
            "uint32"        => "uint32_t".into(),
            "uint64"        => "uint64_t".into(),
            "byte"          => "byte".into(),
            "word"          => "word".into(),
            "double"        => "double".into(),
            "long"          => "long".into(),
            "unsigned_long" => "unsigned long".into(),
            "char"          => "char".into(),
            "size_t"        => "size_t".into(),
            // Pass-through anything else (e.g. class names, template types)
            other           => other.to_owned(),
        }
    }

    /// Infer a C++ type from an expression (best-effort).
    fn infer_expr_type(&self, expr: &PyExpr) -> String {
        match expr {
            PyExpr::Int(_)   => "int".into(),
            PyExpr::Float(_) => "float".into(),
            PyExpr::Bool(_)  => "bool".into(),
            PyExpr::Str(_)   => if self.cfg.arduino_string { "String".into() } else { "const char*".into() },
            PyExpr::Ident(n) => self.var_types.get(n).cloned().unwrap_or_else(|| "auto".into()),
            _                => "auto".into(),
        }
    }

    /// Pre-pass: collect variable types from assignment statements.
    fn infer_var_type_stmt(&mut self, stmt: &PyStmt) {
        if let PyStmt::Assign { target, ann, value, .. } = stmt {
            let ty = ann.as_deref()
                .map(|a| self.py_type_to_cpp(a))
                .or_else(|| value.as_ref().map(|v| self.infer_expr_type(v)));
            if let Some(t) = ty {
                self.var_types.insert(target.clone(), t);
            }
        }
    }
}